version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: "weekly"

  - package-ecosystem: npm
    directory: /bindings/javascript/dev_server
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /bindings/javascript
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /train
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: daily
